### ISSUE TITLE
Implement search.gov for {beta.}get.gov

### ISSUE THREAD

**Issue by calerubensteingsa** [cisagov/get.gov#126]
Updated 5/16

AC:
- [x] Ask the search.gov team to index the beta.get.gov site at [search@gsa.gov](mailto:search@gsa.gov)
- [x] Test the indexed site with a number of test queries. 
- [x] Generate site map (https://github.com/cisagov/getgov-home/issues/124)
- [ ] Display custom message when no results are found.

Search.gov documentation on setting up search on [cloud.gov page](https://search.gov/get-started/searchgov-for-cloudgov-pages.html). Note that some of the details on that documentation page are specific to Jekyll sites. 

Dependent on cisagov/manage.get.gov#618 and cisagov/manage.get.gov#620

**Comment by erinysong** [comment]
I'd may have a better idea of how the newline text element should be handled if I look more closely at your code, but the first thing that comes to mind as a quick fix is also checking if the childNodes contains 1 newline element (under the condition this only happens when our search results are empty) and displaying the No results found message under that condition. Happy to talk over this on a call too!
