### ISSUE TITLE
Remove reference to state abbreviation from page because it is confusing to federal requestors 

### ISSUE THREAD

**Issue by vickyszuchin** [cisagov/get.gov#202]
### Issue description

Remove reference to state on beta.get.gov/Domain/Before you request a domain section. This is irrelevant for federal requestors and may be confusing. 

![image](https://github.com/cisagov/get.gov/assets/144387994/2af3e138-0302-4192-bc33-f2e86a787f18)

### Acceptance criteria

- [ ] Remove "In most instances, this requires including your state’s two-letter abbreviation.” from page

### Additional context

Identified in pre-launch testing. See [issues](https://docs.google.com/document/d/1GvNzvdFOHL8jIiuDfmcxAFXeXXpbkoQx4XkRtAfSVOw/edit)

### Links to other issues

Related to: #[1682](https://github.com/cisagov/manage.get.gov/issues/1682)

**Comment by PaulKuykendall** [comment]
reference - here's a bookmark to the pre-launch notes: 
https://docs.google.com/document/d/1GvNzvdFOHL8jIiuDfmcxAFXeXXpbkoQx4XkRtAfSVOw/edit#bookmark=id.7eiketfh6auu

**Comment by Katherine-Osos** [comment]
Ok, I see the confusion here. In the [pre-launch notes](https://docs.google.com/document/d/1GvNzvdFOHL8jIiuDfmcxAFXeXXpbkoQx4XkRtAfSVOw/edit?disco=AAABDYrm_mY), we indicated that the sentence needs to be removed for "federal" registrants within the request form. That was done via another ticket, and that update should remain in place: #[1682](https://github.com/cisagov/manage.get.gov/issues/1682)

However, **no update was needed for the info site**. Therefore, this ticket for get.gov was unnecessary because the info we're sharing on get.gov is meant to cover all org types. It's not specific to federal orgs. 

I agree with @h-m-f-t, the [update made for this ticket](https://github.com/cisagov/get.gov/pull/227) should be reverted. 

cc: @michelle-rago, @gabydisarli
